/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbsensiRouteImport } from './routes/absensi'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAbsensiRouteImport } from './routes/admin-absensi'
import { Route as AdminHelpRouteImport } from './routes/admin-help'
import { Route as AdminInfaqRouteImport } from './routes/admin-infaq'
import { Route as AdminInspeksiRouteImport } from './routes/admin-inspeksi'
import { Route as AdminJadwalRouteImport } from './routes/admin-jadwal'
import { Route as AdminKeuanganRouteImport } from './routes/admin-keuangan'
import { Route as AdminKeuanganSettingsRouteImport } from './routes/admin-keuangan-settings'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminMateriRouteImport } from './routes/admin-materi'
import { Route as AdminSiswaRouteImport } from './routes/admin-siswa'
import { Route as GuruRouteImport } from './routes/guru'
import { Route as GuruAbsensiRouteImport } from './routes/guru-absensi'
import { Route as GuruHelpRouteImport } from './routes/guru-help'
import { Route as GuruLoginRouteImport } from './routes/guru-login'
import { Route as GuruNilaiRouteImport } from './routes/guru-nilai'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InfaqRouteImport } from './routes/infaq'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as KeuanganRouteImport } from './routes/keuangan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MateriRouteImport } from './routes/materi'
import { Route as NilaiRouteImport } from './routes/nilai'
import { Route as SetupRouteImport } from './routes/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsensiRoute = AbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbsensiRoute = AdminAbsensiRouteImport.update({
  id: '/admin-absensi',
  path: '/admin-absensi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/admin-help',
  path: '/admin-help',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInfaqRoute = AdminInfaqRouteImport.update({
  id: '/admin-infaq',
  path: '/admin-infaq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInspeksiRoute = AdminInspeksiRouteImport.update({
  id: '/admin-inspeksi',
  path: '/admin-inspeksi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJadwalRoute = AdminJadwalRouteImport.update({
  id: '/admin-jadwal',
  path: '/admin-jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeuanganRoute = AdminKeuanganRouteImport.update({
  id: '/admin-keuangan',
  path: '/admin-keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeuanganSettingsRoute = AdminKeuanganSettingsRouteImport.update({
  id: '/admin-keuangan-settings',
  path: '/admin-keuangan-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMateriRoute = AdminMateriRouteImport.update({
  id: '/admin-materi',
  path: '/admin-materi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiswaRoute = AdminSiswaRouteImport.update({
  id: '/admin-siswa',
  path: '/admin-siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruRoute = GuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruAbsensiRoute = GuruAbsensiRouteImport.update({
  id: '/guru-absensi',
  path: '/guru-absensi',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruHelpRoute = GuruHelpRouteImport.update({
  id: '/guru-help',
  path: '/guru-help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruLoginRoute = GuruLoginRouteImport.update({
  id: '/guru-login',
  path: '/guru-login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruNilaiRoute = GuruNilaiRouteImport.update({
  id: '/guru-nilai',
  path: '/guru-nilai',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InfaqRoute = InfaqRouteImport.update({
  id: '/infaq',
  path: '/infaq',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganRoute = KeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriRoute = MateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => rootRouteImport,
} as any)
const NilaiRoute = NilaiRouteImport.update({
  id: '/nilai',
  path: '/nilai',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absensi': typeof AbsensiRoute
  '/admin': typeof AdminRoute
  '/admin-absensi': typeof AdminAbsensiRoute
  '/admin-help': typeof AdminHelpRoute
  '/admin-infaq': typeof AdminInfaqRoute
  '/admin-inspeksi': typeof AdminInspeksiRoute
  '/admin-jadwal': typeof AdminJadwalRoute
  '/admin-keuangan': typeof AdminKeuanganRoute
  '/admin-keuangan-settings': typeof AdminKeuanganSettingsRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-materi': typeof AdminMateriRoute
  '/admin-siswa': typeof AdminSiswaRoute
  '/guru': typeof GuruRoute
  '/guru-absensi': typeof GuruAbsensiRoute
  '/guru-help': typeof GuruHelpRoute
  '/guru-login': typeof GuruLoginRoute
  '/guru-nilai': typeof GuruNilaiRoute
  '/help': typeof HelpRoute
  '/infaq': typeof InfaqRoute
  '/jadwal': typeof JadwalRoute
  '/keuangan': typeof KeuanganRoute
  '/login': typeof LoginRoute
  '/materi': typeof MateriRoute
  '/nilai': typeof NilaiRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absensi': typeof AbsensiRoute
  '/admin': typeof AdminRoute
  '/admin-absensi': typeof AdminAbsensiRoute
  '/admin-help': typeof AdminHelpRoute
  '/admin-infaq': typeof AdminInfaqRoute
  '/admin-inspeksi': typeof AdminInspeksiRoute
  '/admin-jadwal': typeof AdminJadwalRoute
  '/admin-keuangan': typeof AdminKeuanganRoute
  '/admin-keuangan-settings': typeof AdminKeuanganSettingsRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-materi': typeof AdminMateriRoute
  '/admin-siswa': typeof AdminSiswaRoute
  '/guru': typeof GuruRoute
  '/guru-absensi': typeof GuruAbsensiRoute
  '/guru-help': typeof GuruHelpRoute
  '/guru-login': typeof GuruLoginRoute
  '/guru-nilai': typeof GuruNilaiRoute
  '/help': typeof HelpRoute
  '/infaq': typeof InfaqRoute
  '/jadwal': typeof JadwalRoute
  '/keuangan': typeof KeuanganRoute
  '/login': typeof LoginRoute
  '/materi': typeof MateriRoute
  '/nilai': typeof NilaiRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/absensi': typeof AbsensiRoute
  '/admin': typeof AdminRoute
  '/admin-absensi': typeof AdminAbsensiRoute
  '/admin-help': typeof AdminHelpRoute
  '/admin-infaq': typeof AdminInfaqRoute
  '/admin-inspeksi': typeof AdminInspeksiRoute
  '/admin-jadwal': typeof AdminJadwalRoute
  '/admin-keuangan': typeof AdminKeuanganRoute
  '/admin-keuangan-settings': typeof AdminKeuanganSettingsRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-materi': typeof AdminMateriRoute
  '/admin-siswa': typeof AdminSiswaRoute
  '/guru': typeof GuruRoute
  '/guru-absensi': typeof GuruAbsensiRoute
  '/guru-help': typeof GuruHelpRoute
  '/guru-login': typeof GuruLoginRoute
  '/guru-nilai': typeof GuruNilaiRoute
  '/help': typeof HelpRoute
  '/infaq': typeof InfaqRoute
  '/jadwal': typeof JadwalRoute
  '/keuangan': typeof KeuanganRoute
  '/login': typeof LoginRoute
  '/materi': typeof MateriRoute
  '/nilai': typeof NilaiRoute
  '/setup': typeof SetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absensi'
    | '/admin'
    | '/admin-absensi'
    | '/admin-help'
    | '/admin-infaq'
    | '/admin-inspeksi'
    | '/admin-jadwal'
    | '/admin-keuangan'
    | '/admin-keuangan-settings'
    | '/admin-login'
    | '/admin-materi'
    | '/admin-siswa'
    | '/guru'
    | '/guru-absensi'
    | '/guru-help'
    | '/guru-login'
    | '/guru-nilai'
    | '/help'
    | '/infaq'
    | '/jadwal'
    | '/keuangan'
    | '/login'
    | '/materi'
    | '/nilai'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absensi'
    | '/admin'
    | '/admin-absensi'
    | '/admin-help'
    | '/admin-infaq'
    | '/admin-inspeksi'
    | '/admin-jadwal'
    | '/admin-keuangan'
    | '/admin-keuangan-settings'
    | '/admin-login'
    | '/admin-materi'
    | '/admin-siswa'
    | '/guru'
    | '/guru-absensi'
    | '/guru-help'
    | '/guru-login'
    | '/guru-nilai'
    | '/help'
    | '/infaq'
    | '/jadwal'
    | '/keuangan'
    | '/login'
    | '/materi'
    | '/nilai'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/absensi'
    | '/admin'
    | '/admin-absensi'
    | '/admin-help'
    | '/admin-infaq'
    | '/admin-inspeksi'
    | '/admin-jadwal'
    | '/admin-keuangan'
    | '/admin-keuangan-settings'
    | '/admin-login'
    | '/admin-materi'
    | '/admin-siswa'
    | '/guru'
    | '/guru-absensi'
    | '/guru-help'
    | '/guru-login'
    | '/guru-nilai'
    | '/help'
    | '/infaq'
    | '/jadwal'
    | '/keuangan'
    | '/login'
    | '/materi'
    | '/nilai'
    | '/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsensiRoute: typeof AbsensiRoute
  AdminRoute: typeof AdminRoute
  AdminAbsensiRoute: typeof AdminAbsensiRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminInfaqRoute: typeof AdminInfaqRoute
  AdminInspeksiRoute: typeof AdminInspeksiRoute
  AdminJadwalRoute: typeof AdminJadwalRoute
  AdminKeuanganRoute: typeof AdminKeuanganRoute
  AdminKeuanganSettingsRoute: typeof AdminKeuanganSettingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMateriRoute: typeof AdminMateriRoute
  AdminSiswaRoute: typeof AdminSiswaRoute
  GuruRoute: typeof GuruRoute
  GuruAbsensiRoute: typeof GuruAbsensiRoute
  GuruHelpRoute: typeof GuruHelpRoute
  GuruLoginRoute: typeof GuruLoginRoute
  GuruNilaiRoute: typeof GuruNilaiRoute
  HelpRoute: typeof HelpRoute
  InfaqRoute: typeof InfaqRoute
  JadwalRoute: typeof JadwalRoute
  KeuanganRoute: typeof KeuanganRoute
  LoginRoute: typeof LoginRoute
  MateriRoute: typeof MateriRoute
  NilaiRoute: typeof NilaiRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absensi': {
      id: '/absensi'
      path: '/absensi'
      fullPath: '/absensi'
      preLoaderRoute: typeof AbsensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-absensi': {
      id: '/admin-absensi'
      path: '/admin-absensi'
      fullPath: '/admin-absensi'
      preLoaderRoute: typeof AdminAbsensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-help': {
      id: '/admin-help'
      path: '/admin-help'
      fullPath: '/admin-help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-infaq': {
      id: '/admin-infaq'
      path: '/admin-infaq'
      fullPath: '/admin-infaq'
      preLoaderRoute: typeof AdminInfaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-inspeksi': {
      id: '/admin-inspeksi'
      path: '/admin-inspeksi'
      fullPath: '/admin-inspeksi'
      preLoaderRoute: typeof AdminInspeksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-jadwal': {
      id: '/admin-jadwal'
      path: '/admin-jadwal'
      fullPath: '/admin-jadwal'
      preLoaderRoute: typeof AdminJadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-keuangan': {
      id: '/admin-keuangan'
      path: '/admin-keuangan'
      fullPath: '/admin-keuangan'
      preLoaderRoute: typeof AdminKeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-keuangan-settings': {
      id: '/admin-keuangan-settings'
      path: '/admin-keuangan-settings'
      fullPath: '/admin-keuangan-settings'
      preLoaderRoute: typeof AdminKeuanganSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-materi': {
      id: '/admin-materi'
      path: '/admin-materi'
      fullPath: '/admin-materi'
      preLoaderRoute: typeof AdminMateriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-siswa': {
      id: '/admin-siswa'
      path: '/admin-siswa'
      fullPath: '/admin-siswa'
      preLoaderRoute: typeof AdminSiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru': {
      id: '/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof GuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru-absensi': {
      id: '/guru-absensi'
      path: '/guru-absensi'
      fullPath: '/guru-absensi'
      preLoaderRoute: typeof GuruAbsensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru-help': {
      id: '/guru-help'
      path: '/guru-help'
      fullPath: '/guru-help'
      preLoaderRoute: typeof GuruHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru-login': {
      id: '/guru-login'
      path: '/guru-login'
      fullPath: '/guru-login'
      preLoaderRoute: typeof GuruLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru-nilai': {
      id: '/guru-nilai'
      path: '/guru-nilai'
      fullPath: '/guru-nilai'
      preLoaderRoute: typeof GuruNilaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infaq': {
      id: '/infaq'
      path: '/infaq'
      fullPath: '/infaq'
      preLoaderRoute: typeof InfaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan': {
      id: '/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof KeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi': {
      id: '/materi'
      path: '/materi'
      fullPath: '/materi'
      preLoaderRoute: typeof MateriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nilai': {
      id: '/nilai'
      path: '/nilai'
      fullPath: '/nilai'
      preLoaderRoute: typeof NilaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsensiRoute: AbsensiRoute,
  AdminRoute: AdminRoute,
  AdminAbsensiRoute: AdminAbsensiRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminInfaqRoute: AdminInfaqRoute,
  AdminInspeksiRoute: AdminInspeksiRoute,
  AdminJadwalRoute: AdminJadwalRoute,
  AdminKeuanganRoute: AdminKeuanganRoute,
  AdminKeuanganSettingsRoute: AdminKeuanganSettingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMateriRoute: AdminMateriRoute,
  AdminSiswaRoute: AdminSiswaRoute,
  GuruRoute: GuruRoute,
  GuruAbsensiRoute: GuruAbsensiRoute,
  GuruHelpRoute: GuruHelpRoute,
  GuruLoginRoute: GuruLoginRoute,
  GuruNilaiRoute: GuruNilaiRoute,
  HelpRoute: HelpRoute,
  InfaqRoute: InfaqRoute,
  JadwalRoute: JadwalRoute,
  KeuanganRoute: KeuanganRoute,
  LoginRoute: LoginRoute,
  MateriRoute: MateriRoute,
  NilaiRoute: NilaiRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
